### ISSUE TITLE
for "UBCF"algorithm, in "REAL_UBCF"function, "sum_s_uk <- colSums(s_uk)"I think should change to sum_s_uk <- colSums(s_uk, na.rm=TRUE)

### ISSUE THREAD

**Issue by LynnMachineLearning0822** [mhahsler/recommenderlab#13]
as the title dexcribes,I think,  for "UBCF"algorithm, in "REAL_UBCF"function, "sum_s_uk <- colSums(s_uk)"I think should change to "sum_s_uk <- colSums(s_uk, na.rm=TRUE)"
I'm not sure whether it's a bug.

**Comment by mhahsler** [comment]
Thanks! I have added this to the development version on github.
