### ISSUE TITLE
still showing progress despite, progress = FALSE 

### ISSUE THREAD

**Issue by pspachtholz** [mhahsler/recommenderlab#15]
I am using R 3.4.1. and the latest development version from github (also tested with the CRAN version). 

As the title says, setting progress = FALSE in the evaluate function does not have an effect and evaluate still outputs progress for the folds in crossvalidation.

**Comment by mhahsler** [comment]
Hi. I finally found some time to look at this. I just checked and could not reproduce the problem. Can you post some code that reproduces the behavior? Thanks!

**Comment by anjoshigor** [comment]
I have an example:

```r
ratings <- read.csv('csv/rating_final.csv')
binaryMatrix <- as(ratings,"binaryRatingMatrix")
scheme <- evaluationScheme(binaryMatrix, method = "cross-validation", k=5, train = 0.7, given = -1)
methods <- list(
          popular = list(name = "POPULAR", param = NULL), 
          `user-based CF` = list(name = "UBCF", param = list(method = "cosine", nn = 3)),
          `item-based CF` = list(name = "IBCF", param = list(method = "cosine", k = 3)),
          AR = list(name="AR", param = list(supp=0.05,conf=0.5))
          )
results <- evaluate(scheme, methods, type="topNList", n = c(1,2,5), progress = FALSE)
 ```
Although the **progress** parameter is false, the output is:
```console
POPULAR run fold/sample [model time/prediction time]
	 1  [0sec/0.116sec] 
	 2  [0sec/0.112sec] 
	 3  [0sec/0.144sec] 
	 4  [0.004sec/0.16sec] 
	 5  [0.004sec/0.172sec] 
UBCF run fold/sample [model time/prediction time]
	 1  [0.004sec/0.232sec] 
	 2  [0sec/0.228sec] 
	 3  [0sec/0.228sec] 
	 4  [0.004sec/0.22sec] 
	 5  [0.004sec/0.224sec] 
IBCF run fold/sample [model time/prediction time]
	 1  [0.04sec/0.02sec] 
	 2  [0.04sec/0.028sec] 
	 3  [0.04sec/0.032sec] 
	 4  [0.04sec/0.02sec] 
	 5  [0.036sec/0.016sec] 
AR run fold/sample [model time/prediction time]
	 1  [0.028sec/0.812sec] 
	 2  [0.032sec/0.788sec] 
	 3  [0.036sec/1.072sec] 
	 4  [0.044sec/0.996sec] 
	 5  [0.04sec/1.012sec] 
```

The **csv/rating_final.csv** file is the one inside this [zip file](https://archive.ics.uci.edu/ml/machine-learning-databases/00232/) on UCI repository.

I think this just occurs when using methods list and probably due [this code](https://github.com/cran/recommenderlab/blob/d973a639814700f2083fcbb2ae420142511ecc9a/R/evaluate.R#L33). 

Shouldn't the **progress** parameter be passed down?

Sorry if it wasn't the best way to comment.
