### ISSUE TITLE
Matrix way too big. Can I use key - values database instead? Question

### ISSUE THREAD

**Issue by ran88dom99** [mhahsler/recommenderlab#17]
I have a ratings database of the user_id,item_id,rating style in R. If I use the whole thing or even anything larger than 1k users by 200 items as a base for a matrix my computer runs out of memory. Data.table manages to work on same dataset lightning quick. Can recommenderlab use such a dataset type directly without having to matrix it?

**Comment by mhahsler** [comment]
recommenderlab stores data as a sparse matrix which does not store missing values. Have a look at `? realRatingMatrix` I have nit looked at how to convert a data.table to a sparse matrix. Maybe this page helps: https://stackoverflow.com/questions/43217893/is-there-a-data-table-representation-of-sparse-matrices-objects

**Comment by ran88dom99** [comment]
I think I did but converting was impossible. now I seek online-pca? to be honest I do not remember.
https://www.kaggle.com/philippsp/book-recommender-collaborative-filtering-shiny 
I will get back to you possibly soon
