### ISSUE TITLE
funkSVD starting values for U and V

### ISSUE THREAD

**Issue by vkummer** [mhahsler/recommenderlab#21]
Hi, I would like to try other starting values for U and V in funkSVD. No matter what I do, `tcrossprod(fsvd$U, fsvd$V)` results in very similar predictions for the missing values per row but that's not what it is supposed to do. I already tried many different parameter combinations but that didn't help. So I was hoping, other starting values (e.g. `matrix(rnorm(nrow(x)*k),nrow = nrow(x), ncol = k) ` might solve the problem. I tried to copy the function and initialize U and V with random numbers but R always crashes. Would it be possible to make the initialization of U and V a definable variable as well? Or do you have any other solution? Thanks.

**Comment by mhahsler** [comment]
The function is adapted from package rrecsys by Ludovik Coba and Markus Zanker. I am not sure that I can help you with this.
