### ISSUE TITLE
Is this line a typo, for the symbol "/"

### ISSUE THREAD

**Issue by jackyrx** [mhahsler/recommenderlab#24]
Inside normalize.R,

in line 94 - 96,
```
if(method_id==2) { ## Z-score
        data@x <- data@x/rep(sds, colCounts(x))
}
```

Will this be a typo of the operator symbol division ("/")?
Since this is the function of normalize under Z-Score method.

while the line 83 - 85, are using multiply ("*")
```
if(method_id==2) { ## Z-Score
        data@x <- data@x*rep(sds, rowCounts(x))
}
```

Thank you.

**Comment by mhahsler** [comment]
Hi! Thank you for the bug report. The code on GitHub is now fixed. The fix will be part of the next release. You can install the package directly from GitHub for now.
