### ISSUE TITLE
Is HybridRecommender.R missing some commands

### ISSUE THREAD

**Issue by jackyrx** [mhahsler/recommenderlab#25]
Since I have read through Hybrid Recommender.R ,
and I saw there is missing the below in order to set the HYBRID as the recommender entry.

```
recommenderRegistry$set_entry(
  method="HYBRID", dataType = "realRatingMatrix", fun= HybridRecommender,
  description="Hybrid Recommender")

```

Also, besides this issue, 
is the HybridRecommender only performs prediction (both rating and TopNList) and only able to evaluate the ratings only?
Is any chance/ plan that extending that to evaluation on topNList (ROC confusion matrix)?

Thank you.

**Comment by mhahsler** [comment]
HybridRecommender is actually not a recommender algorithm, but just a wrapper that contains recommender algorithms. So it is similar to the function Recommender and that is why it is not in the registry. 

About the prediction: Can you add some code I can run that shows the problem?

**Comment by mhahsler** [comment]
This is now resolved. See `? HybridRecommender`.
