### ISSUE TITLE
lower bound for topN in IBCF for binaryRatingMatrix

### ISSUE THREAD

**Issue by spedygiorgio** [mhahsler/recommenderlab#3]
I'm using recommenderlab on a binaryratingmatrix evaluating an item based CF recommender. I noticed that the minumum topN is ten whichever n I set and I wonder whether this is an error.

recc_model.ibcf <- Recommender(data = data_train, method = "IBCF",parameter = list(method = "Jaccard",k=4)) #item based with 4 items
model_details <- getModel(recc_model.ibcf)
#recc_model.ubcf <- Recommender(data = data_train, method = "UBCF",parameter = list(method = "Jaccard",nn=30)) 
#model_details <- getModel(recc_model.ubcf)

n_recommended <- 2L
recc_predicted <- predict(object = recc_model.ibcf, newdata = data_test, n = n_recommended)

#Recommendations as ‘topNList’ with n = 10 for 4205 users. 
#iI would have expected with n=2 instead than 10

recc_user_1 <- recc_predicted@items[[1]]
ard_user_1 <- recc_predicted@itemLabels[recc_user_1]
ard_user_1

[db4RS.zip](https://github.com/mhahsler/recommenderlab/files/470066/db4RS.zip)
The attached zip files contains an rdata where train_data and test_data are saved

**Comment by mhahsler** [comment]
Hi Giorgio,

Thank you for the bug report. It is now fixed in the development version on github.

-Michael
