### ISSUE TITLE
Some problems about "realRatingMatrix" 

### ISSUE THREAD

**Issue by ErtyumPX** [mhahsler/recommenderlab#30]
I'm new in R programming and i don't realy know much thing about it but i have to do a simple project. I need to make a something like in this site. https://www.r-bloggers.com/recommender-systems-101-a-step-by-step-practical-example-in-r/

(codes from that website)

1 - library("recommenderlab")
2 - data <- read.csv("collected_data.csv")
3 - affinity.data<-read.csv("collected_data.csv")
4 - affinity.matrix<- as(affinity.data,"realRatingMatrix") 

  This is where i can't pass.
  After this, i get a data at the environment tab and types "Formal class realRatingMatrix" but i saw in another video, it types "Large class realRatingMatrix"

5 - Rec.model<-Recommender(affinity.matrix[1:5000], method = "UBCF") 

  Btw my .csv file has 1000 lines.
  After this code, iget an error and it says "Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  index larger than maximal 4".

I need this programme immediately, i hope someone can answer it in this day.

**Comment by mhahsler** [comment]
I cannot debug the problem without a reproducible example. Please email me your data file.
