### ISSUE TITLE
Possible to evaluate a hybridRecommender?

### ISSUE THREAD

**Issue by yckoong** [mhahsler/recommenderlab#32]
Hi @mhahsler , i'm curious to know is it possible to evaluate a hybridRecommender? I'm trying to search on the internet regarding this question but fail to find any. 

There is a way to evaluate different methods (e.g AR, IBCF, POPULAR, RANDOM & UBCF), and with `evaluate` function provided in `recommenderlab` it's easily for user to compare the performance between methods. 
![image](https://user-images.githubusercontent.com/29967331/56490449-d98c1400-6517-11e9-8d9a-57840d2bc75c.png)

Is there a way to evaluate a `hybridRecommender` **together with other methods**?
```
# Below is the sample dataset
m <- matrix(sample(c(0,1), 50, replace=TRUE), nrow=5, ncol=10,
            dimnames=list(users=paste("u", 1:5, sep=''),
                           items=paste("i", 1:10, sep='')))

# Convert matrix into binaryRatingMatrix
b <- as(m, "binaryRatingMatrix")

# Compute HybridRecommender
recom <- recommenderlab::HybridRecommender(
         Recommender(b, method = "AR"),
         Recommender(b, method = "IBCF"),
         Recommender(b, method = "POPULAR"),
         Recommender(b, method = "UBCF"),
         weights = c(.25, .25, .25, .25))

# Set Evaluation Scheme
scheme <- evaluationScheme(b, 
                           method="split",
                           train=0.9,
                           given=1)

# Set list of algorithms to evaluate
algorithms <- list(
  "Association rules" = list(name = "AR"),
  "Item-based CF" = list(name = "IBCF"),
  "Popular items" = list(name = "POPULAR"),
  "Random items" = list(name = "RANDOM"),
  "User-based CF" = list(name = "UBCF"),
  "Hybrid" = list(name = "recom")
  )

# run algorithms, predict next n movies
results <- evaluate(scheme, algorithms, n=c(1, 3, 5, 10, 15, 20))

# Draw ROC curve
plot(results, annotate = 1:4, legend="bottomright")
```
Hope to hear from you!

**Comment by mhahsler** [comment]
Unfortunately, this is not implemented and needs some major work. Hopefully, someone will help with this.

**Comment by mhahsler** [comment]
This is now possible. See `? HybridRecommender`

**Comment by willoutcault** [comment]
@yckoong Hello, to follow up I have the same issue and have not found the solution in the 
`? HybridRecommender` documentation. To reiterate I created a hybrid model using the following code.

`recom <- HybridRecommender(
  Recommender(getData(esCross, "known"), method = "UBCF"),
  Recommender(getData(esCross, "known"), method = "RANDOM"),
  weights = c(.5, .5)
)`

I want to use the `evaluate` function so that I can create an ROC plot. Any pointers?

**Comment by mhahsler** [comment]
Hi,

I just checked the README on Github and found:

## New Features
* Recommender gained method "HYBRID" to create hybrid recommenders. Now hybrid recommenders can also be used in evaluate().

However, you need to install the development version from Github, I still need to submit a new release to CRAN.
