### ISSUE TITLE
How the argument "goodRating" work in function "calcPredictionAccuracy"

### ISSUE THREAD

**Issue by pinnnnn** [mhahsler/recommenderlab#33]
Hi, 

I want to build a recommendation model by applying this package, however when I evaluate the performance of the model, I'm not quite understand the function "calcPredictionAccuracy".

Is the "goodRating" argument means the threshold that the the item would be recommended if the rating is higher than this threshold?

I used part of the example code in the document as follows:

https://pastebin.com/6WyXt6PC

I found that none of the prediction rating 'p' of the member u6662 is higher than the threshold, so I thought it means that no items would be recommended when evaluating, while the TP of this member is 28, and I'm confused about it. 

Is there anyone knows how this thing work?

**Comment by mhahsler** [comment]
I think the documentation was a little sparse on this one. I have added the following to `?calcPredictionAccuracy`

> If the ratings are a "topNList" and the observed data is a "realRatingMatrix" then \code{goodRating} is used to determine what rating in \code{data} is considered a good rating for calculating binary classification measures. This means that an item in the topNList is considered a true positive if it has a rating of \code{goodRating} or better in the observed data.

I hope this helps.

**Comment by pinnnnn** [comment]
I think I've figured it out.

The goodRating is for deciding whether the observed data should be classified to positive or negative, and for topNList method it gives the top n items as recommendation only conditional on the order of the value of predicting rating regardless of the value itself or any threshold.

It helps a lot. Thanks for helping!

**Comment by mhahsler** [comment]
You are welcome.
