### ISSUE TITLE
RECOM_RANDOM why not assign rownames?

### ISSUE THREAD

**Issue by aliko-str** [mhahsler/recommenderlab#35]
## create random ratings (Z-scores)
    ratings <- matrix(rnorm(nrow(newdata)*ncol(newdata)),
      nrow=nrow(newdata), ncol=ncol(newdata),
      dimnames=list(NULL, model$labels))

Why NULL in dimnames, and not user ids? 
as(ratings, "data.frame") fails without row names.

**Comment by mhahsler** [comment]
Thank you for the bug report. This is now fixed in the development version on GitHub.

There is no coercion from topNList to data.frame. Coerce the topNlist into a list or a matrix.
