### ISSUE TITLE
could I get the rank or score from the predict()? and reformat the result into datafram

### ISSUE THREAD

**Issue by celinexuclover** [mhahsler/recommenderlab#39]
Dear Sir, 
  I am using   "binaryRatingMatrix"  as input. and using 
  seg_pre_ubcf<-Recommender(method = "UBCF", param=list(method="Cosine")) %>% 
  recommenderlab::predict(seg_pred_matrix, n = 20)

to pipe the result. 
then I can use as(seg_pre_ubcf, "list") to check the result.  (produce the recomendation for each cust_id)
in the result, i have a list of item_id for a specific custmoer_id, but I am not sure, is the first item_id is the best recommendation from UBCF model for this customer_id (I having n=20, is the first item_id means it rank as the first, all the all 20 item_id having same probability/similarity score to the specific customer? )

could I use existing function to reformat it?
I did not find one then I creat my own lop, as 
 
 seg2df <- function(top_list){
  tmp <- as(top_list, "list")
  n <- length(names(tmp))
  out <- tibble(rownum = NA, item_id = NA) 
  for (i in 1:n){
    list_item <- tibble(rownum = i,
                        item_id= tmp[[i]])
    out <- rbind(out, list_item)
  }
  
  out <- out %>% 
    group_by(FK_Customer_No) %>% 
    mutate(rank = row_number()) %>% 
    ungroup()
  return(out)
}

any suggestion? input? thank you!

**Comment by mhahsler** [comment]
Hi,

please ask this question on [stackoverflow.com](https://stackoverflow.com/). You will need a reproducible example.

Regards,
Michael
