### ISSUE TITLE
Regression from version 0.2-5 to 0.2-6 in Recommender.predict behavior

### ISSUE THREAD

**Issue by SrinivasAiyar** [mhahsler/recommenderlab#42]
I get the following error in 0.2-6 which I didn't see with 0.2-5:

Error in neighbors[, x] : incorrect number of dimensions
Calls: getRecos ... predict -> .local -> <Anonymous> -> sapply -> lapply -> FUN
Execution halted

**Comment by mhahsler** [comment]
Thank you for this report. Please send me the code that produces this error. Thanks, Michael

**Comment by SrinivasAiyar** [comment]
Hi Michael,

I have attached the code with the data file that reproduces the error.  I will also upload to Github.


Srinivas K Aiyar (KSri)
Chief Architect, Zenoti
(425) 765 0760 (USA)
[https://ci6.googleusercontent.com/proxy/qj-TnjsF0PYg9Obxex5sbGDHk4YU772ioQaHBVMl39qEBiHDBxDlJ5JWNqW_VnQkgjB-OKR6bOg5eodo-6WppS85vjbpbUsi0A=s0-d-e1-ft#https://www.zenoti.com/_images/signature-logo-1.jpg]<https://www.zenoti.com/>

[https://ci3.googleusercontent.com/proxy/2RMAHncJvbDDWKhL6OVxwHMzHOTdXwTQbfT4R5Zvq69hfo0L5HCYudbwG-LPjt-9meypDegrwvdAeHClpnY7-7PDEkjL2zdhVcg=s0-d-e1-ft#https://www.zenoti.com/es/email-signature-banner.png]<https://www.zenoti.com/es>



________________________________

**Comment by mhahsler** [comment]
Looks like GitHub does not keep attachments. Please email it directly to mhahsler [at] lyle.smu.edu.

Thanks,
Michael

**Comment by SrinivasAiyar** [comment]
Attached the zip file.


Srinivas K Aiyar (KSri)
Chief Architect, Zenoti
(425) 765 0760 (USA)
[https://ci6.googleusercontent.com/proxy/qj-TnjsF0PYg9Obxex5sbGDHk4YU772ioQaHBVMl39qEBiHDBxDlJ5JWNqW_VnQkgjB-OKR6bOg5eodo-6WppS85vjbpbUsi0A=s0-d-e1-ft#https://www.zenoti.com/_images/signature-logo-1.jpg]<https://www.zenoti.com/>

[https://ci3.googleusercontent.com/proxy/2RMAHncJvbDDWKhL6OVxwHMzHOTdXwTQbfT4R5Zvq69hfo0L5HCYudbwG-LPjt-9meypDegrwvdAeHClpnY7-7PDEkjL2zdhVcg=s0-d-e1-ft#https://www.zenoti.com/es/email-signature-banner.png]<https://www.zenoti.com/es>



________________________________
