### ISSUE TITLE
MovieLens metadata

### ISSUE THREAD

**Issue by david-cortes** [mhahsler/recommenderlab#44]
The MovieLens 100k dataset comes with some side information about the users. This package has the ratings and item side information (title, year, genres) already - would be nice if it also included the user's side info.

**Comment by mhahsler** [comment]
I have added the user metadata in the development version on GitHub. Please check and see if it works correctly.

**Comment by david-cortes** [comment]
Working correctly thanks. Although I couldn't install the package with devtools or remotes, had to download the repo and use `R CMD`.

**Comment by mhahsler** [comment]
Great. Thanks for letting me know.
