### ISSUE TITLE
BIN_UBCF() of RECOM_UBCF does not return topNList when type==''topNList"

### ISSUE THREAD

**Issue by meftasadat** [mhahsler/recommenderlab#5]
Hi Dr. Hahsler,

I noticed that for a 'binaryRatingMatrix', no matter what the type is (i.e. "topNList", "ratings"), BIN_UBCF() always returns a realRatingMatrix. Please see Line #74 in  https://github.com/mhahsler/recommenderlab/blob/master/R/RECOM_UBCF.R.

For example, if I set ` results = evaluate(scheme, c("UBCF","IBCF"), type = "topNList")`
I should get a topNList as results. I also noticed IBCF does return a topNList (line #66 - #68 in https://github.com/mhahsler/recommenderlab/blob/master/R/RECOM_IBCF.R)

Can you please tell me if this is an actual issue and can be fixed. I added the following lines before line #74 in RECOM_UBCF.R and the accuracy in case of a binaryRatingMatrix increases.
`if(type=='topNList'){`
  `top_N= (getTopNLists(ratings, n=ncol(ratings)))`
   ` top_N <- bestN(top_N, n)`
   ` return(top_N)`
`}`

**Comment by mhahsler** [comment]
Thanks for the bug report. This should now be fixed in the development version on github.
