### ISSUE TITLE
Fatal error after open package

### ISSUE THREAD

**Issue by IrinaMax** [mhahsler/recommenderlab#6]
Hi, I had problems with installation of recommenderlab, almost 2 days it did not want to installed in Rstudio even manually downloaded. Now try to download and install every dependencies manually. I start with 'irlba' manually and then try to install recommenderlab again, sound it was installed,but Rstudio immediately come up with Fatal Error and end of Session! :( I rapid action and the same result. Can you please recommend me what to do? Thanks.
https://www.dropbox.com/s/d62ci0vujpdxkiu/Screenshot%202017-02-07%2000.11.41.png?dl=0

**Comment by mhahsler** [comment]
Recommenderlab contains no compiled code so it is very unlikely to produce a fatal error. Looks like R dies when loading package proxy. Try to load proxy by itself. Make sure that you have the latest version of R and RStrudio.

**Comment by IrinaMax** [comment]
Thank you so much! Yes, its dies during loading proxy. I have Version 0.99.879, and last week i try to install 1.0.136 but its did not open after installation, so I back to the 0.99.879, will try new one again later. R is 3.3.2.
So I try to install and load proxy, but Fatal Error come up again during 'registry'.
I try to 'registry', then Fatal Error come up again during 'arules'.
I load 'arules' and 'base' now it still give Fatal Error when i load 'recommenderlab'.
when i installing recommenderlab I got mistake:
`install.packages('recommenderlab', dependencies=TRUE)
Installing package into ‘/Users/irinamahmudjanova/Library/R/3.3/library’
(as ‘lib’ is unspecified)
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/src/contrib/recommenderlab_0.2-1.tar.gz'
Content type 'unknown' length 1431460 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

ERROR: failed to lock directory ‘/Users/irinamahmudjanova/Library/R/3.3/library’ for modifying
Try removing ‘/Users/irinamahmudjanova/Library/R/3.3/library/00LOCK-recommenderlab’
Warning in install.packages :
  installation of package ‘recommenderlab’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/xk/zqkqv02j627g4_jw9hh8hfym0000gn/T/RtmpxIrXnQ/downloaded_packages’`
then  I  removed 00LOCK in terminal, coz I thoght it could be problem:
`rm -rf 00LOCK-recommenderlab`
But it is still finish with the same Fatal Error, which already scare me... I want to work with this package!

**Comment by mhahsler** [comment]
I think you need a complete reinstall of R and all packages.
