### ISSUE TITLE
Use more stable Rd cross reference

### ISSUE THREAD

**Issue by jaganmn** [mhahsler/recommenderlab#67]
Parallel to https://github.com/mhahsler/arules/issues/81, it would be safer to refer to `ngCMatrix-class` here:

https://github.com/mhahsler/recommenderlab/blob/ae9d03465fc30f49d9096d49696737f70ab2d404/man/realRatingMatrix-class.Rd#L101

**Comment by mhahsler** [comment]
Fixed. Thanks!
