### ISSUE TITLE
predict function can't input for realRatingMatrix

### ISSUE THREAD

**Issue by AlexYoung757** [mhahsler/recommenderlab#9]
thank you for mhahsler，i meet with difficulties
after tansform the data to realRatingMatrix，then i use predict function but the results  as follow
[[1]]
character(0)

[[2]]
character(0)

[[3]]
character(0)

so i transform the data to binaryRatingMatrix，it can work. i don't know why

**Comment by mhahsler** [comment]
Please send me a code example that recreates this problem.

**Comment by AlexYoung757** [comment]
@mhahsler ,thank you for your reply, here is my code 
`
traindata.cast <- dcast(train.rating.sample, user_id ~ item_id,value.var = "rating")
ml.useritem <- traindata.cast[,-1]
ml.useritem[1:3, 1:6]

ml.useritem <- as.matrix(ml.useritem)
# ml.ratingMatrix <- as(ml.useritem, "realRatingMatrix")  
ml.ratingMatrix <- as(ml.useritem, "binaryRatingMatrix")  
ml.ratingMatrix


as(ml.ratingMatrix , "matrix")[1:10, 1:10]
as(ml.ratingMatrix , "list")[[1]][1:10]


# recommenderRegistry$get_entries(dataType = "realRatingMatrix")
recommenderRegistry$get_entries(dataType = "binaryRatingMatrix")
ml.recommModel <- Recommender(ml.ratingMatrix[1:7940], method = "IBCF")
ml.recommModel

ml.predict1 <- predict(ml.recommModel, ml.ratingMatrix[7941:7943])
ml.predict1
as(ml.predict1, "list")  
`
i have commented the realRatingMatrix, it can't input

**Comment by mhahsler** [comment]
I need a complete example with data and code.

**Comment by AlexYoung757** [comment]
@mhahsler thanks ,i will send a email include data and code
